// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZai-cdeVXlA88Zqo1RecXNJ71-i7Kdko',
    appId: '1:611649124061:web:d6b8f414c5a13816938d34',
    messagingSenderId: '611649124061',
    projectId: 'flutter-project-assist-virtual',
    authDomain: 'flutter-project-assist-virtual.firebaseapp.com',
    storageBucket: 'flutter-project-assist-virtual.firebasestorage.app',
    measurementId: 'G-V50VZE9DF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1y8NauzVVVePiLxFKoNvIRNqrJ-IhoS0',
    appId: '1:611649124061:android:4ef8bc299035f5c4938d34',
    messagingSenderId: '611649124061',
    projectId: 'flutter-project-assist-virtual',
    storageBucket: 'flutter-project-assist-virtual.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrN3ahZjmuztcgZwe_M_hRmpRraH3qS0o',
    appId: '1:611649124061:ios:ad125195f9132c26938d34',
    messagingSenderId: '611649124061',
    projectId: 'flutter-project-assist-virtual',
    storageBucket: 'flutter-project-assist-virtual.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrN3ahZjmuztcgZwe_M_hRmpRraH3qS0o',
    appId: '1:611649124061:ios:ad125195f9132c26938d34',
    messagingSenderId: '611649124061',
    projectId: 'flutter-project-assist-virtual',
    storageBucket: 'flutter-project-assist-virtual.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZai-cdeVXlA88Zqo1RecXNJ71-i7Kdko',
    appId: '1:611649124061:web:f89cfc62f26778c9938d34',
    messagingSenderId: '611649124061',
    projectId: 'flutter-project-assist-virtual',
    authDomain: 'flutter-project-assist-virtual.firebaseapp.com',
    storageBucket: 'flutter-project-assist-virtual.firebasestorage.app',
    measurementId: 'G-9KGZYFXJQY',
  );

}